stages:
  data_load:
    cmd: python src/stages/data_load.py --config=params.yaml
    deps:
    - src/stages/data_load.py
    - data/manual/test.csv
    - data/manual/test2.csv
    params:
    - data_load
    outs:
    - data/raw/iris.csv
