stages:
  data_load:
    cmd: python src/stages/data_load.py --config=params.yaml
    deps:
    - src/stages/data_load.py
    params:
    - base
    - data_load
    outs:
    - data/raw/iris.csv
  featurize:
    cmd: python src/stages/featurize.py --config=params.yaml
    deps:
    - src/stages/featurize.py
    - data/raw/iris.csv
    params:
    - base
    - featurize
    outs:
    - data/train/iris_train.csv
    - data/test/iris_test.csv
  train:
    cmd: python src/stages/train.py --config=params.yaml
    deps:
    - src/stages/train.py
    - data/train/iris_train.csv
    - data/test/iris_test.csv
    params:
    - base
    - train
    - featurize
    outs:
    - models/logistic_regression.pkl
  evaluate:
    cmd: python src/stages/evaluate.py --config=params.yaml
    deps:
    - src/stages/evaluate.py
    - models/logistic_regression.pkl
    - data/train/iris_train.csv
    - data/test/iris_test.csv
    params:
    - base
    - evaluate
    - train
    metrics:
    - reports/metrics/logistic_regression/metrics.json