base:
  seed: 39

data_load:
  data_raw_csv_path: 'data/raw/iris.csv'

featurize:
  data_train_csv_path: 'data/train/iris_train.csv'
  data_test_csv_path: 'data/test/iris_test.csv'

train:
  logistic_regression_path: 'models/logistic_regression.pkl'

evaluate:
  metrics_path: 'reports/metrics/logistic_regression/metrics.json'